name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
  
      - name: Use Node.js
        uses: actions/setup-node@v4.2.0
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 20.x
          cache: 'pnpm'
  
      - name: Clear hosted tool-cache for corepack
        # See: [actions/setup-node/issues/1222](https://github.com/actions/setup-node/issues/1222#issuecomment-2673608477)
        if: runner.os == 'Windows'
        run: Remove-Item -Recurse -Force (Get-Command corepack.cmd).Path
        shell: pwsh
  
      - name: Install Corepack
        # See: [actions/setup-node/issues/1222](https://github.com/actions/setup-node/issues/1222)
        run: npm i -g --force corepack && corepack enable && pnpm i
        shell: bash

      - name: Build
        run: |
          pnpm b

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .vitepress/dist
